# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2024-09-28T10:36:04+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import VideoLinkResponse

app = FastAPI(
    title='Video Duplicate Checker API',
    version='1.0.0',
    servers=[{'url': '/'}],
)


@app.post(
    '/check-video-duplicate',
    response_model=VideoLinkResponse,
    tags=['API для проверки дубликатов видео'],
)
def post_check_video_duplicate() -> VideoLinkResponse:
    """
    Проверка видео на дублирование
    """
    pass
